In [37]:
import numpy as np
from numpy.linalg import inv

In [43]:
A = np.array([[2,4,5], [3,3,6], [2, 7, 8]])
B = np.array([[3,3,6], [2,4,5], [4, 0, 1]])
print(A)
print(B)

[[2 4 5]
 [3 3 6]
 [2 7 8]]
[[3 3 6]
 [2 4 5]
 [4 0 1]]


In [45]:
prod = np.dot(A, B)
print(prod)

[[34 22 37]
 [39 21 39]
 [52 34 55]]


In [49]:
Bin = inv(B)

roughA = np.dot(prod,Bin)
print(roughA)

[[2. 4. 5.]
 [3. 3. 6.]
 [2. 7. 8.]]


In [38]:
Ain = inv(A)

In [39]:
Ain

array([[ 2.        , -0.33333333, -1.        ],
       [ 1.33333333, -0.66666667, -0.33333333],
       [-1.66666667,  0.66666667,  0.66666667]])

In [40]:
print(np.dot(A, Ain))

[[ 1.00000000e+00 -2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -8.88178420e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
